// Custom shader file for dm_villa.bsp
// Generated by Q3Map2 (ydnar)
// Do not edit! This file is overwritten on recompiles.

dm_villa/7C7E779F4281DDF73AFC9A289ADD3927
{
	qer_editorimage textures/sg_stone/stone_stonewall.jpg
	q3map_nonplanar
	q3map_lightmapMergable
	q3map_lightmapSize 1024 1024
	q3map_lightmapBrightness 2.0
	q3map_lightmapsamplesize 4
	{
		tcgen lightmap
		map maps/dm_villa/lm_0000.tga
		rgbGen identity
	}
	{
		map textures/sg_stone/stone_stonewall.jpg
		blendFunc filter
	}
}

dm_villa/200E29B64DC4EFF5EE2E52DDD18C5A51
{
	qer_editorimage textures/sg_wood2/wood_wood6.jpg
	q3map_nonplanar
	q3map_lightmapMergable
	q3map_lightmapSize 1024 1024
	q3map_lightmapBrightness 2.0
	q3map_lightmapsamplesize 4
	{
		tcgen lightmap
		map maps/dm_villa/lm_0000.tga
		rgbGen identity
	}
	{
		map textures/sg_wood2/wood_wood6.jpg
		blendFunc filter
	}
}

dm_villa/1D924075D16D145E1F9BAD57DECC4B50
{
	qer_editorimage textures/sg_wood2/wood_wood21.jpg
	q3map_nonplanar
	q3map_lightmapMergable
	q3map_lightmapSize 1024 1024
	q3map_lightmapBrightness 2.0
	q3map_lightmapsamplesize 4
	{
		tcgen lightmap
		map maps/dm_villa/lm_0000.tga
		rgbGen identity
	}
	{
		map textures/sg_wood2/wood_wood21.jpg
		blendFunc filter
	}
}

dm_villa/4C4D09B738EF92543C316501BB4AF4CC
{
	qer_editorimage textures/sg_dirt/dirt_erosion3.jpg
	q3map_nonplanar
	q3map_lightmapMergable
	q3map_lightmapSize 1024 1024
	q3map_lightmapBrightness 2.0
	q3map_lightmapsamplesize 4
	{
		tcgen lightmap
		map maps/dm_villa/lm_0000.tga
		rgbGen identity
	}
	{
		map textures/sg_dirt/dirt_erosion3.jpg
		blendFunc filter
	}
}

