// Custom shader file for br_villa.bsp
// Generated by Q3Map2 (ydnar)
// Do not edit! This file is overwritten on recompiles.

br_villa/B3B2C73B2C585D66924DD69F49DF4C70
{
	qer_editorimage textures/sg_stone/stone_stonewall.jpg
	q3map_nonplanar
	q3map_lightmapMergable
	q3map_lightmapSize 1024 1024
	q3map_lightmapBrightness 2.0
	q3map_lightmapsamplesize 4
	{
		tcgen lightmap
		map maps/br_villa/lm_0000.tga
		rgbGen identity
	}
	{
		map textures/sg_stone/stone_stonewall.jpg
		blendFunc filter
	}
}

br_villa/7B8BD3B3090501967A2B4ADC872C5CEA
{
	qer_editorimage textures/sg_wood2/wood_wood6.jpg
	q3map_nonplanar
	q3map_lightmapMergable
	q3map_lightmapSize 1024 1024
	q3map_lightmapBrightness 2.0
	q3map_lightmapsamplesize 4
	{
		tcgen lightmap
		map maps/br_villa/lm_0000.tga
		rgbGen identity
	}
	{
		map textures/sg_wood2/wood_wood6.jpg
		blendFunc filter
	}
}

br_villa/A78A3735396BEB5D4FAAA2319BEB6E65
{
	qer_editorimage textures/sg_wood2/wood_wood21.jpg
	q3map_nonplanar
	q3map_lightmapMergable
	q3map_lightmapSize 1024 1024
	q3map_lightmapBrightness 2.0
	q3map_lightmapsamplesize 4
	{
		tcgen lightmap
		map maps/br_villa/lm_0000.tga
		rgbGen identity
	}
	{
		map textures/sg_wood2/wood_wood21.jpg
		blendFunc filter
	}
}

br_villa/C03A2F241F7A0CD2308982FD0A92C26A
{
	qer_editorimage textures/sg_dirt/dirt_erosion3.jpg
	q3map_nonplanar
	q3map_lightmapMergable
	q3map_lightmapSize 1024 1024
	q3map_lightmapBrightness 2.0
	q3map_lightmapsamplesize 4
	{
		tcgen lightmap
		map maps/br_villa/lm_0000.tga
		rgbGen identity
	}
	{
		map textures/sg_dirt/dirt_erosion3.jpg
		blendFunc filter
	}
}

